dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: "20883"


#load other properties , application-*.yml
#separated by ","


spring:
  profiles:
    active: mybatis

